---
kind: pipeline
type: kubernetes
name: build-mopidy

metadata:
  namespace: drone

steps:
- name: kaniko
  image: banzaicloud/drone-kaniko
  settings:
    registry: registry.home.sud0.com
    repo: mopidy
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

